name: CH341SER

on:
  push:
    branches: [ "main", "master", "ubuntu" ]
  pull_request:
    branches: [ "main", "master", "ubuntu" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: initialize
        uses: actions/checkout@v2
      - name: update
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -fy
      - name: dependencies
        run: sudo apt install -f -y linux-headers-$(uname -r)
      - name: build
        run: make
